<?xml version="1.0" ?>
<robot name="jueying" 
    xmlns:xacro="http://www.ros.org/wiki/xacro">

    <material name="black">
        <color rgba="0.0 0.0 0.0 1.0"/>
    </material>
    <material name="blue">
        <color rgba="0.0 0.0 0.8 1.0"/>
    </material>
    <material name="green">
        <color rgba="0.0 0.8 0.0 1.0"/>
    </material>
    <material name="grey">
        <color rgba="0.2 0.2 0.2 1.0"/>
    </material>
    <material name="silver">
        <color rgba="0.913725490196 0.913725490196 0.847058823529 1.0"/>
    </material>
    <material name="orange">
        <color rgba="1.0 0.423529411765 0.0392156862745 1.0"/>
    </material>
    <material name="brown">
        <color rgba="0.870588235294 0.811764705882 0.764705882353 1.0"/>
    </material>
    <material name="red">
        <color rgba="0.8 0.0 0.0 1.0"/>
    </material>
    <material name="white">
        <color rgba="1.0 1.0 1.0 1.0"/>
    </material>

    <!--以下物理参数根据绝影的实际情况设置-->
    <xacro:property name="motor_torque" value="0.0"/>
    <xacro:property name="motor_vec" value="0.0"/>
    <xacro:property name="motor_damp" value="1.2"/>
    <xacro:property name="motor_fric" value="0.1"/>
    <xacro:property name="PI" value="3.14159265359"/>
    <xacro:property name="sx_l" value="0.204"/>
    <xacro:property name="sx_r" value="0.0746"/>
    <xacro:property name="sy_z" value="0.295"/>
    <xacro:property name="sy_y" value="0.051"/>
    <xacro:property name="sy_x" value="0.038"/>
    <xacro:property name="sy_l" value="0.051"/>
    <xacro:property name="sy_r" value="0.019"/>
    <xacro:property name="sk_z" value="0.3053"/>
    <xacro:property name="sk_y" value="0.028"/>
    <xacro:property name="sk_x" value="0.028"/>
    <xacro:property name="sk_r" value="0.0305"/>

    <link name="origin_link">
    </link>
    <joint name="origin_baselink_joint" type="fixed">
        <origin xyz="0 0 0.6" rpy="0 0 0"/>
        <parent link="origin_link"/>
        <child link="base_link"/>
    </joint>
    <link name="base_link">
        <inertial>
            <origin xyz="0.0030652 0.0043949 0.015248" rpy="0 0 0" />
            <mass value="30.0" />
            <inertia ixx="0.15234" ixy="0.00092094" ixz="-0.0095582" iyy="0.68188" iyz="0.00091552" izz="0.64094" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://jueying_description/meshes/base_link.STL" />
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="0.76 0.18 0.18"/>
            </geometry>
        </collision>
        <collision>
            <origin xyz="-0.38 0 0" rpy="0 0 0" />
            <geometry>
                <sphere radius="0.09"/>
            </geometry>
        </collision>
        <collision>
            <origin xyz="0.38 0 0" rpy="0 0 0" />
            <geometry>
                <sphere radius="0.09"/>
            </geometry>
        </collision>
    </link>

    <xacro:macro name="jueying_leg" params="name is_f is_l">
        <link name="${name}_HipX">
            <inertial>
                <origin xyz="0.0 ${is_l*0.038} 0.0" rpy="0 0 0" />
                <mass value="3.0" />
                <inertia ixx="0.00084975" ixy="2.5128E-05" ixz="-3.1095E-05" iyy="0.0016235" iyz="1.9684E-05" izz="0.0012084" />
            </inertial>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <mesh filename="package://jueying_description/meshes/${name}_HipX.STL" />
                </geometry>
                <material name="white"/>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="${PI/2.0} 0 0" />
                <geometry>
                    <cylinder length="${sx_l}" radius="${sx_r}"/>
                </geometry>
            </collision>
        </link>
        <joint name="${name}_HipX_joint" type="revolute">
            <origin xyz="${is_f*0.317} ${is_l*0.136} 0" rpy="0 0 0" />
            <parent link="base_link" />
            <child link="${name}_HipX" />
            <axis xyz="1 0 0" />
            <limit lower="-0.39" upper="0.39" effort="37.8" velocity="13.6" />
            <dynamics damping="${motor_damp}" friction="${motor_fric}" />
        </joint>
        <link name="${name}_HipY">
            <inertial>
                <origin xyz="0.0 ${is_l*0.026983} -0.047138" rpy="0 0 0" />
                <mass value="6.0" />
                <inertia ixx="0.0091835" ixy="-5.5596E-05" ixz="-0.00026799" iyy="0.0095232" iyz="-0.0011185" izz="0.0023439" />
            </inertial>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <mesh filename="package://jueying_description/meshes/${name}_HipY.STL" />
                </geometry>
                <material name="white"/>
            </visual>
            <collision>
                <origin xyz="0 0 ${-sy_z/2}" rpy="0 0 0" />
                <geometry>
                    <box size="${sy_x} ${sy_y} ${sy_z}"/>
                </geometry>
            </collision>
            <collision>
                <origin xyz="0 0 ${-sy_z}" rpy="${PI/2.0} 0 0" />
                <geometry>
                    <cylinder length="${sy_l}" radius="${sy_r}"/>
                </geometry>
            </collision>
        </link>
        <joint name="${name}_HipY_joint" type="revolute">
            <origin xyz="0.0 ${is_l*0.037} 0.0" rpy="0 0 0" />
            <parent link="${name}_HipX" />
            <child link="${name}_HipY" />
            <axis xyz="0 -1 0" />
            <limit lower="-2.27" upper="0.18" effort="58.3" velocity="13.4" />
            <dynamics damping="${motor_damp}" friction="${motor_fric}" />
        </joint>
        <link name="${name}_Knee">
            <inertial>
                <origin xyz="0.0 0.0 -0.14462" rpy="0 0 0" />
                <mass value="1.0" />
                <inertia ixx="0.0048214" ixy="-9.1437E-08" ixz="8.5221E-05" iyy="0.0048402" iyz="1.3168E-06" izz="5.8603E-05" />
            </inertial>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <mesh filename="package://jueying_description/meshes/${name}_Knee.STL" />
                </geometry>
                <material name="white"/>
            </visual>
            <collision>
                <origin xyz="0 0 ${-sk_z/2}" rpy="0 0 0" />
                <geometry>
                    <box size="${sk_x} ${sk_y} ${sk_z}"/>
                </geometry>
            </collision>
            <collision>
                <origin xyz="0 0 ${-sk_z}" rpy="0 0 0" />
                <geometry>
                    <sphere radius="${sk_r}"/>
                </geometry>
            </collision>
        </link>
        <joint name="${name}_Knee_joint" type="revolute">
            <origin xyz="0 0 -0.3" rpy="0 0 0" />
            <parent link="${name}_HipY" />
            <child link="${name}_Knee" />
            <axis xyz="0 -1 0" />
            <limit lower="0.66" upper="2.73" effort="58.3" velocity="13.4" />
            <dynamics damping="${motor_damp}" friction="${motor_fric}" />
        </joint>
    </xacro:macro>

    <xacro:jueying_leg name="FL" is_f= "1" is_l= "1" />
    <xacro:jueying_leg name="FR" is_f= "1" is_l="-1" />
    <xacro:jueying_leg name="HL" is_f="-1" is_l= "1" />
    <xacro:jueying_leg name="HR" is_f="-1" is_l="-1" />
</robot>
  
